name: Config

on:
  workflow_dispatch:
  repository_dispatch:
    types: [app-config]

jobs:
  dispatch-receive:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      security-events: write
      packages: read
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.WORKFLOW_TOKEN }}
        repository: tarathep/app-poc-receive-config
        event-type: Receive Step 2
        client-payload: '{"repository": "${{ github.repository }}" , "ref": "${{ github.ref }}", "test_secret": "${{ secrets.TEST_SECRET }}", "github_token": "${{ secrets.WORKFLOW_TOKEN }}"}'